services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: laptracker
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  server:
    build: ./server
    env_file: .env
    depends_on:
      - db
    ports:
      - "8080:8080"

  web:
    build: ./web
    env_file: .env
    depends_on:
      - server
    ports:
      - "5173:5173"

volumes:
  dbdata:
